defaults: &defaults
  roles:
    - admin
    - moderator
    - user
  default_role: user
  base_url: 'http://localhost:3000'

development:
  <<: *defaults


test:
  <<: *defaults

production:
  <<: *defaults

